### ISSUE TITLE
Не компилируется, валится с ошибкой

### ISSUE THREAD

**Issue by bolkonskiy** [GyverLibs/CharDisplay#1]
error: variable or field '_addUnix' declared void

**Comment by GyverLibs** [comment]
В коде библиотеки нет _addUnix

**Comment by MakcimKe** [comment]
![image](https://user-images.githubusercontent.com/46790069/235898355-6e1e7665-a549-4ffe-b46e-a2b0184a2a44.png)
есть в данном файле \CharDisplay\src\utils.h:3:15

**Comment by GyverLibs** [comment]
В библиотеке нет этого файла
![image](https://user-images.githubusercontent.com/84599917/235899154-070dfc4c-d1ef-4c8f-8875-f49c0beb8be9.png)

**Comment by bolkonskiy** [comment]
> В библиотеке нет этого файла ![image](https://user-images.githubusercontent.com/84599917/235899154-070dfc4c-d1ef-4c8f-8875-f49c0beb8be9.png)

При установке из Arduino IDE есть:
<img width="235" alt="image" src="https://user-images.githubusercontent.com/42890450/235935222-407f5cec-4ef5-4a95-bc83-b8283aa97a99.png">

**Comment by GyverLibs** [comment]
принял, сейчас перезалью релиз
